//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int Sno { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string BikeNumber { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> DateofService { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public string Reference { get; set; }
        public string Remark { get; set; }
        public string BikePic { get; set; }
        public string CustomerType { get; set; }
    }
}
