//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMechanic
    {
        public int MechanicId { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string ShowRoom { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string MechAddress { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BikeServiced { get; set; }
        public string Remark { get; set; }
    }
}
